name: 'opa-policy-sync'
description: 'A GitHub action that syncs OPA policies'
author: 'OpsVerse (https://opsverse.io)'

branding:
  icon: 'activity'
  color: 'white'

inputs:
  opaServerUrl:
    description: 'OPA Serveer URL'
    required: true
    default: ''
  opaServerAuthToken:
    description: 'OPA Server Auth Token'
    required: true
    default: ''
  opaServerInput:
    description: 'OPA Server Input'
    required: true
    default: ''
  opaServerPackageName:
    description: 'OPA Server Package Name'
    required: true
    default: ''
  opaPolicyPath:
    description: 'OPA Policy Path'
    required: true
    default: ''
  skipTlsValidation:
    description: 'Skip TLS validation. Get the data from OPA by ignoring the certificate.'
    required: false
    default: "false"
  recurseDirs:
    description: 'Recurse directories for policies.'
    required: false
    default: "true"

runs:
  using: node20
  main: dist/index.js
